export const CARD_THEMES = {
  american: {
    cardBg:      '#FFFBF0',
    accent:      '#CC0000',
    tag:         'AMERICAN KITCHEN',
    nameColor:   '#1A1A1A',
    labelColor:  '#CC0000',
    chipBg:      '#F5F0E8',
    chipBorder:  '#E0D5C5',
    chipText:    '#3D2B1F',
    descColor:   '#4a3a2a',
    ingBorder:   '#CC0000',
    stepNumBg:   '#CC0000',
    stepNumText: '#fff',
    tipBg:       '#FFF3CD',
  },
  italian: {
    cardBg:      '#F5ECD7',
    accent:      '#C4622D',
    tag:         'TRATTORIA ITALIANA',
    nameColor:   '#1A1A1A',
    labelColor:  '#C4622D',
    chipBg:      '#EDE4CC',
    chipBorder:  '#D5CEB5',
    chipText:    '#2D1A0A',
    descColor:   '#4a3520',
    ingBorder:   '#C4622D',
    stepNumBg:   '#2D5016',
    stepNumText: '#F5ECD7',
    tipBg:       '#FFF5E0',
  },
  asian: {
    cardBg:      '#1A1A1A',
    accent:      '#FFD700',
    tag:         'ASIAN KITCHEN',
    nameColor:   '#FFD700',
    labelColor:  '#FFD700',
    chipBg:      '#2A2A2A',
    chipBorder:  '#FFD70044',
    chipText:    '#d4c090',
    descColor:   '#c0a880',
    ingBorder:   '#FFD700',
    stepNumBg:   '#FFD700',
    stepNumText: '#1A1A1A',
    tipBg:       '#242420',
  },
  latin: {
    cardBg:      '#fff',
    accent:      '#D4622D',
    tag:         'LATIN FLAVORS',
    nameColor:   '#1A1A1A',
    labelColor:  '#D4622D',
    chipBg:      '#FFF5F0',
    chipBorder:  '#E8C5B0',
    chipText:    '#3D1A0F',
    descColor:   '#4a2a1a',
    ingBorder:   '#D4622D',
    stepNumBg:   '#D4622D',
    stepNumText: '#fff',
    tipBg:       '#FFF8F0',
  },
  mediterranean: {
    cardBg:      '#fff',
    accent:      '#0047AB',
    tag:         'MEDITERRANEAN',
    nameColor:   '#1A1A1A',
    labelColor:  '#0047AB',
    chipBg:      '#F0F4FF',
    chipBorder:  '#C5D0E8',
    chipText:    '#0A1F3D',
    descColor:   '#2a3a5a',
    ingBorder:   '#0047AB',
    stepNumBg:   '#0047AB',
    stepNumText: '#fff',
    tipBg:       '#F0F8FF',
  },
  indian: {
    cardBg:      '#6B2D3E',
    accent:      '#FF9933',
    tag:         'INDIAN SPICE',
    nameColor:   '#f0d8b8',
    labelColor:  '#FF9933',
    chipBg:      '#5a1a2e',
    chipBorder:  '#FF993355',
    chipText:    '#f0d8b8',
    descColor:   '#e0c0a0',
    ingBorder:   '#FF9933',
    stepNumBg:   '#FF9933',
    stepNumText: '#1A1A1A',
    tipBg:       '#5a2030',
  },
  steakhouse: {
    cardBg:      '#1C1C1C',
    accent:      '#B8860B',
    tag:         'THE STEAKHOUSE',
    nameColor:   '#d0b080',
    labelColor:  '#B8860B',
    chipBg:      '#2A2A2A',
    chipBorder:  '#B8860B44',
    chipText:    '#d0b080',
    descColor:   '#c0a060',
    ingBorder:   '#B8860B',
    stepNumBg:   '#B8860B',
    stepNumText: '#1C1C1C',
    tipBg:       '#252010',
  },
  healthy: {
    cardBg:      '#fff',
    accent:      '#7D9B76',
    tag:         'WHOLESOME KITCHEN',
    nameColor:   '#1A1A1A',
    labelColor:  '#2D4A2D',
    chipBg:      '#F0F5EF',
    chipBorder:  '#C5D5C0',
    chipText:    '#1D3A1D',
    descColor:   '#3a5a3a',
    ingBorder:   '#7D9B76',
    stepNumBg:   '#7D9B76',
    stepNumText: '#fff',
    tipBg:       '#F5FFF3',
  },
};

export const DEFAULT_THEME = CARD_THEMES.american;
